
reactions = {
	'783813544520712213': { #rules channel
		'881792967386480690': {
			'<:teacode_icon_dark:972803589145776189>': '🌱 Members',
			'<:teacode_icon_white:972803591452622858>': '🌱 Members',
		},
	},
	'802521765586010132': { #get-roles channel
		'904481592532164658': {
			'⚽': 'Html / Css',
			# '🏀': 'Less',
			# '🏈': 'Sass',
			# '⚾': 'Tailwind Css',
			# '🎾': 'Bootstrap',
			'🏐': 'Javascript / Typescript',
			# '🏉': 'Typescript',
			# '🎱': 'jQuery',
			'🏓': 'Angular',
			'🏸': 'VueJs',
			'⛳': 'ReactJs',
			# '🥋': 'EmberJs',
			# '🥊': 'Svelte',
			# '🏑': 'JSON',
			# '🥌': 'XML',
			# '🥏': 'YAML',
			# '🪂': 'Nest JS',
			# '⛸': 'Next JS',
			# '🥅': 'Nuxt JS',
			# '🛹': 'Gatsby',
			'🐇': 'NodeJs',
			'🐅': 'ExpressJs',
			'🐘': 'Php',
			'🐞': 'Laravel',
			'🦆': 'Symfony',
			# '🐦': 'CodeIgniter',
			'🦈': 'C# / DotNet',
			# '🐟': 'VB.Net',
			# '🐬': 'DotNet',
			'🦕': 'Java',
			'🦖': 'Spring / Spring Boot',
			'🐍': 'Python',
			'🦎': 'Django',
			'🐉': 'Flask',
			# '🐢': 'Ruby',
			# '🐌': 'Ruby on Rails',
			# '🦅': 'Swift',
			# '🐁': 'Go Lang',
			# '⚙': 'Rust',
			# '👾': 'C#',
			# '🤖': 'C++',
			# '💀': 'Unity',
			'🦔': 'Assembly',
			'🦝': 'C / C++',
		},
		'904484461826154546': {
			'🪛': 'Git',
			# '🔧': 'GitHub',
			# '🔨': 'GitLab',
			# '🗡️': 'Bitbucket',
			# '⛏️': 'Git Kraken',
			# '🔩': 'Phabricator',
			# '🪓': 'SourceTree',
			# '🪚': 'Svn',
			'🚲': 'Docker',
			'🛵': 'Kubernetes',
			'🏍️': 'Jenkins',
			'🛺': 'Ansible',
			# '🚗': 'SonarQube',
			# '🚄': 'Selenium',
			# '🚛': 'Gradle',
			'🪟': 'Windows',
			'🐧': 'Linux',
			'🌪️': 'Mac',
			'☄️': 'Windows Terminal',
			# '🔥': 'Cmder',
			'🌊': 'Bash',
			# '🌤️': 'iTerm2',
			# '🌀': 'AWS - Amazon Web Services',
			# '⚡': 'Microsoft Azure',
			# '💧': 'Google Cloud',
			# '☂️': 'Alibaba Cloud',
			# '❄️': 'IBM Cloud',
			# '🌙': 'Oracle Cloud',
			# '☀️': 'Salesforce',
			# '☁️': 'SAP',
		},
		'904492639393566780': {
			'🏚': 'SQL',
			'🏘': 'NoSQL',
			# '🏪': 'PL / SQL',
			# '🏣': 'Transact-SQL',
			'⛩': 'GraphQL',
			'🏰': 'MySQL',
			'🗼': 'PostgreSQL',
			'🏭': 'SQLite',
			'🏟': 'SQL Server',
			'🏤': 'Oracle',
			'🏢': 'MongoDB',
			'🛖': 'Redis',
			'⛺': 'Firebase',
			# '🏦': 'Cassandra',
			# '🏯': 'RethinkDB',
			# '🏛': 'Neo4j',
		},
		'904502258375479386': {
			'🍃': 'IntelliJ IDEA',
			# '🍂': 'WebStorm',
			# '🍏': 'PhpStorm',
			# '🍎': 'PyCharm',
			# '🌹': 'Rider (.Net)',
			# '🍑': 'RubyMine',
			# '🍒': 'DataGrip',
			'🍀': 'Android Studio',
			'🌺': 'Visual Studio',
			'🌷': 'VSCode',
			# '🌱': 'Atom',
			'🍓': 'Sublime Text',
			# '🌻': 'Brackets',
			'🌾': 'Eclipse',
			# '🥑': 'NetBeans',
			# '🌼': 'CodeBlocks',
			'💐': 'Vim',
			# '🍇': 'Notepad++',
			'📷': 'Adobe Photoshop',
			'⌨️': 'Adobe Illustrator',
			'📹': 'Adobe After Effects',
			# '⏲️': 'Adobe Lightroom',
			'🎚️': 'Adobe XD',
			# '📟': 'Adobe InDesign',
			# '📼': 'Adobe Premiere Pro',
			# '⌚': 'Autodesk Maya',
			# '🕹️': 'Autodesk 3ds Max',
			'📺': 'Blender',
			# '🎮': 'Adobe Fuse CC',
			# '🎙️': 'Cinema 4D',
			# '📻': 'Sketch',
			# '☎️': 'SketchUp',
			'🖲️': 'Figma',
			# '🇽': 'Xamarin Forms',
			# '🇳': 'Xamarin Native',
			'🇽': 'Xamarin Forms / Native',
			'🇰': 'Kotlin',
			'🇷': 'React Native',
			# '🇩': 'Dart',
			# '🇫': 'Flutter',
			'🇫': 'Flutter / Dart',
			'🇨': 'Ionic',
			'🇦': 'Android',
			'🇮': 'iOS',
		},
		'904507027403980862': {
			# '🍊': 'Technical Referent',
			# '🥭': 'Technical Lead',
			'🥝': 'Database Administrator',
			# '🥥': 'Programmer',
			# '🍋': 'Developer',
			# '🍇': 'Software Developer',
			'🍎': 'Software Engineer',
			'🍐': 'Web Developer',
			'🍓': 'Web Designer',
			# '🍈': 'FullStack Developer',
			'🥑': 'Frontend Developer',
			'🍅': 'Backend Developer',
			'🫐': 'Mobile Developer',
			'🍍': 'Game Developer',
			'🖊️': 'Data Scientist',
			# '✒️': 'Data Architect',
			# '🖌️': 'Data Analyst',
			'✏️': 'Cloud Architect',
			# '🖍️': 'Cloud Developer',
			# '📏': 'Data Engineer',
			# '🖋️': 'Cloud Engineer',
			'⛵': 'DevOps / DevSecOps',
			'🚢': 'DevOps Engineer',
			# '🚀': 'DevOps Evangelist',
			# '✈️': 'DevOps Software Developer',
			'🧪': 'Software Tester',
			# '🌡':	'Quality Assurance',
			# '🌁': 'Designer',
			'💾': 'Graphic Designer',
			'📷': 'UI/UX Designer',
			# '📷': 'UI Designer',
			# '🖲️': 'UX Designer',
			# '📽️': 'Film Maker / VFX',
			'🦬': 'Systems Administrator',
			# '🐴': 'Network Administrator',
			'🦉': 'Network Engineer',
			# '🐻‍❄️': 'Network Architect',
			# '🦣': 'IT Security Engineer',
			# '🦅': 'Security Specialist',
			# '🐪': 'Security Systems Administrator',
			'🐿️': 'Security Engineer',
            '🥦': 'Business Intelligence',
		},
		'904518697383759903': {
			'🥗': 'Artificial Intelligence',
			'🍕': 'Machine Learning',
			'🥟': 'DevOps / DevSecOps',
			'🍛': 'Blockchain',
			'🍩': 'VR / AR',
			'🧇': 'Cyber Security',
			'🧆': 'Cloud',
			'🥮': 'Big Data',
			'🎂': 'Internet Of Things',
			'🧀': 'Robotics / Electronics',
			'🍲': 'E-Commerce',
			'🍪': 'Development',
			'🍙': 'Game Development',
			'🌰': 'Mobile Development',
			'🍚': 'Data Science',
			'🍘': 'Computer Sciences',
			'🍨': 'Start-Ups / Entrepreneurship',
			'🥧': 'Project Management (Agile/Scrum)',
            # '🥘': 'Business Intelligence',
			'🍿': 'Web 3.0',
			'🥘': 'Open Source Software (OSS)',
		},
		'930480136166469683': {
			'☕': 'Hangouts',
			'💭': 'Communication',
			'🎥': 'Workshops',
			'💻': 'Coding Challenges',
			'📱': 'Mock Interview',
			'🗓': 'Community Events',
			'📢': 'Announcements / Polls',
			'💀': 'Hide Archive',
		},
		'969927727580868628': {
			'🎓': 'Student',
			'💼': 'Employee',
			'🎒': 'Freelancer',
			'👔': 'Entrepreneur',
			'🔎': 'Looking for a job',
		},
	},
}
