reactions = {
	'796732247470112769': { #polls
		'938141030673428550': {
			'🟤': 'Play Chess',
			'🟡': 'Coding Challenges'
		},
		'952311197594701895': {
			'🇾': 'Learn Programming'
		},
		'942529169223462923': {
			'🇾': 'Learn French'
		},
		'929867978969845770': {
			'🇾': 'Learn German'
		}
	},
	'783813544520712213': { #rules channel
		'881792967386480690': {
			'<:teacode_bordred:844450911941165086>': '🌱│Members'
		},
	},
	'802521765586010132': { #get-roles channel
		'904481592532164658': {
			'⚽': 'Html / Css',
			'🏀': 'Less',
			'🏈': 'Sass',
			'⚾': 'Tailwind Css',
			'🎾': 'Bootstrap',
			'🏐': 'Javascript',
			'🏉': 'Typescript',
			'🎱': 'jQuery',
			'🏓': 'Angular',
			'🏸': 'VueJs',
			'⛳': 'ReactJs',
			'🥋': 'EmberJs',
			'🥊': 'Svelte',
			'🏑': 'JSON',
			'🥌': 'XML',
			'🥏': 'YAML',
			'🪂': 'Nest JS',
			'⛸': 'Next JS',
			'🥅': 'Nuxt JS',
			'🛹': 'Gatsby',
		},
		'904484461826154546': {
			'🪛': 'Git',
			'🔧': 'Github',
			'🔨': 'GitLab',
			'🗡️': 'Bitbucket',
			'⛏️': 'Git Kraken',
			'🔩': 'Phabricator',
			'🪓': 'SourceTree',
			'🪚': 'Svn',
		},
		'904486579677052948': {
			'🚲': 'Docker',
			'🛵': 'Kubernetes',
			'🏍️': 'Jenkins',
			'🛺': 'Ansible',
			'🚗': 'SonarQube',
			'🚄': 'Selenium',
			'🚛': 'Gradle',
		},
		'904488442254225428': {
			'🪟': 'Windows',
			'🐧': 'Linux',
			'🌪️': 'Mac',
			'☄️': 'Windows Terminal',
			'🔥': 'Cmder',
			'🌊': 'Bash',
			'🌤️': 'iTerm2',
			'🌀': 'AWS - Amazon Web Services',
			'⚡': 'Microsoft Azure',
			'💧': 'Google Cloud',
			'☂️': 'Alibaba Cloud',
			'❄️': 'IBM Cloud',
			'🌙': 'Oracle Cloud',
			'☀️': 'Salesforce',
			'☁️': 'SAP',
		},
		'904490216847458365': {
			'🐇': 'NodeJs',
			'🐅': 'ExpressJs',
			'🐘': 'Php',
			'🐞': 'Laravel',
			'🦆': 'Symfony',
			'🐦': 'CodeIgniter',
			'🦈': 'C#',
			'🐟': 'VB.Net',
			'🐬': 'DotNet',
			'🦕': 'Java',
			'🦖': 'Spring / Spring Boot',
			'🐍': 'Python',
			'🦎': 'Django',
			'🐉': 'Flask',
			'🐢': 'Ruby',
			'🐌': 'Ruby on Rails',
			'🦅': 'Swift',
			'🐁': 'Go Lang',
			'⚙': 'Rust',
		},
		'904492639393566780': {
			'🏚': 'SQL',
			'🏘': 'NoSQL',
			'🏪': 'PL / SQL',
			'🏣': 'Transact-SQL',
			'⛩': 'GraphQL',
			'🏰': 'MySQL',
			'🗼': 'PostgreSQL',
			'🏭': 'SQLite',
			'🏟': 'SQL Server',
			'🏤': 'Oracle',
			'🏢': 'MongoDB',
			'🛖': 'Redis',
			'⛺': 'Firebase',
			'🏦': 'Cassandra',
			'🏯': 'RethinkDB',
			'🏛': 'Neo4j',
		},
		'904495036916449362': {
			'🇽': 'Xamarin Forms',
			'🇳': 'Xamarin Native',
			'🇰': 'Kotlin',
			'🇷': 'React Native',
			'🇩': 'Dart',
			'🇫': 'Flutter',
			'🇨': 'Ionic',
			'🇦': 'Android',
			'🇮': 'iOS',
		},
		'904499785426432001': {
			'📷': 'Adobe Photoshop',
			'⌨️': 'Adobe Illustrator',
			'📹': 'Adobe After Effects',
			'⏲️': 'Adobe Lightroom',
			'🎚️': 'Adobe XD',
			'📟': 'Adobe InDesign',
			'📼': 'Adobe Premiere Pro',
			'⌚': 'Autodesk Maya',
			'🕹️': 'Autodesk 3ds Max',
			'📺': 'Blender',
			'🎮': 'Adobe Fuse CC',
			'🎙️': 'Cinema 4D',
			'📻': 'Sketch',
			'☎️': 'SketchUp',
			'🖲️': 'Figma',
		},
		'904502258375479386': {
			'🍃': 'IntelliJ IDEA',
			'🍂': 'WebStorm',
			'🍏': 'PhpStorm',
			'🍎': 'PyCharm',
			'🌹': 'Rider (.Net)',
			'🍑': 'RubyMine',
			'🍒': 'DataGrip',
			'🍀': 'Android Studio',
			'🌺': 'Visual Studio',
			'🌷': 'VSCode',
			'🌱': 'Atom',
			'🍓': 'Sublime Text',
			'🌻': 'Brackets',
			'🌾': 'Eclipse',
			'🥑': 'NetBeans',
			'🌼': 'CodeBlocks',
			'💐': 'Vim',
			'🍇': 'Notepad++',
		},
		'904504466852700160': {
			'👾': 'C#',
			'🤖': 'C++',
			'💀': 'Unity',
			'🦔': 'Assembly',
			'🦝': 'C Language',
		},
		'904507027403980862': {
			'🍊': 'Technical Referent',
			'🥭': 'Technical Lead',
			'🥝': 'Database Administrator',
			'🥥': 'Programmer',
			'🍋': 'Developer',
			'🍇': 'Software Engineer',
			'🍐': 'Web Developer',
			'🍓': 'Web Designer',
			'🍈': 'FullStack Developer',
			'🥑': 'Frontend Developer',
			'🍅': 'Backend Developer',
			'🫐': 'Mobile Developer',
			'🍍': 'Game Developer',
			'🍎': 'Software Developer',
		},
		'904512821285503036': {
			'🖊️': 'Data Scientist',
			'✒️': 'Data Architect',
			'🖌️': 'Data Analyst',
			'✏️': 'Cloud Architect',
			'🖍️': 'Cloud Developer',
			'📏': 'Data Engineer',
			'🖋️': 'Cloud Engineer',
			'⛵': 'DevOps / DevSecOps',
			'🚢': 'DevOps Engineer',
			'🚀': 'DevOps Evangelist',
			'✈️': 'DevOps Software Developer',
			'🧪': 'Software Tester',
			'🌡':	'Quality Assurance',
		},
		'904515671080198164': {
			'🌁': 'Designer',
			'💾': 'Graphic Designer',
			'📷': 'UI Designer',
			'🖲️': 'UX Designer',
			'📽️': 'Film Maker / VFX',
			'🦬': 'Systems Administrator',
			'🐴': 'Network Administrator',
			'🦉': 'Network Engineer',
			'🐻‍❄️': 'Network Architect',
			'🦣': 'IT Security Engineer',
			'🦅': 'Security Specialist',
			'🐪': 'Security Systems Administrator',
			'🐿️': 'Security Engineer',
		},
		'904518697383759903': {
			'🥗': 'Artificial Intelligence',
			'🍕': 'Machine Learning',
			'🥟': 'DevOps / DevSecOps',
			'🍛': 'Blockchain',
			'🍩': 'VR / AR',
			'🧇': 'Cyber Security',
			'🧆': 'Cloud',
			'🥮': 'Big Data',
			'🎂': 'Internet Of Things',
			'🧀': 'Robotics / Electronics',
			'🍲': 'E-Commerce',
			'🍪': 'Developpement',
			'🍙': 'Game Developement',
			'🌰': 'Mobile Developement',
			'🍚': 'Data Science',
			'🍘': 'Computer Sciences',
			'🍨': 'Start-Ups / Entrepreneurship',
			# '🍿': '',
			'🥧': 'Project Management (Agile/Scrum)',
			'🥘': 'Business Intelligence',
		},
		'-----------': {
			'☕': 'Hangout',
			'💭': 'Communication',
			'🎥': 'Workshops',
			'🧠': 'Coding Challenges',
			'📂': 'Mock Interview',
		},
	},
}